plugins { id 'com.android.application' }
android {
 namespace 'tv.aurora.player'
 compileSdk 35
 signingConfigs { debug { storeFile rootProject.file('debug.keystore'); storePassword 'android'; keyAlias 'androiddebugkey'; keyPassword 'android' } }
 defaultConfig { applicationId 'tv.aurora.player'; minSdk 23; targetSdk 35; versionCode 5; versionName '0.5.0' }
 compileOptions { coreLibraryDesugaringEnabled true; sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies {
 coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:2.1.4"
 implementation 'androidx.media3:media3-exoplayer:1.9.3'
 implementation 'androidx.media3:media3-exoplayer-hls:1.9.3'
 implementation 'androidx.media3:media3-exoplayer-dash:1.9.3'
 implementation 'androidx.media3:media3-ui:1.9.3'
}
