import 'catalog.dart';

/// The 284 factual national-network reference positions previously verified
/// against the 2026-07-29 DIRECTV via Satellite lineup in the original app.
/// Only imported IPTV provider streams are displayed; no channels or listings
/// are fabricated. This is not a DIRECTV interface or affiliation.
class ChannelLineup {
  static const reference = <String,int>{
    'METV': 77,
    'COZI TV': 80,
    'GRIT': 81,
    'BOUNCE TV': 82,
    'GREAT': 83,
    'START TV': 84,
    'TRUE CRMZ': 85,
    'MOVIESPHERE GOLD': 86,
    'ION MYSTERY': 88,
    'DIRECTV 4K LIVE': 105,
    'DIRECTV 4K LIVE 2': 106,
    'KIDS MIX CHANNEL': 189,
    'DIRECTV NEWS MIX': 200,
    'CNN': 202,
    'HLN': 204,
    'DIRECTV HD SPORTSMIX': 205,
    'ESPN': 206,
    'ESPNEWS': 207,
    'ESPNU': 208,
    'ESPN2': 209,
    'ESPN PLUS': 210,
    'NFL REDZONE': 211,
    'NFL NETWORK': 212,
    'MLB NETWORK': 213,
    'RACER NETWORK': 214,
    'NHL NETWORK': 215,
    'NBA TV': 216,
    'TENNIS CHANNEL': 217,
    'GOLF CHANNEL': 218,
    'FS1': 219,
    'CBS SPORTS NETWORK': 221,
    'CELEBRITY SHOPPING': 223,
    'SHOP LC': 226,
    'GEM SHOPPING NETWORK': 228,
    'HGTV': 229,
    'MAGNOLIA NETWORK': 230,
    'FOOD NETWORK': 231,
    'COOKING CHANNEL': 232,
    'GAME SHOW NETWORK': 233,
    'TASTEMADE': 235,
    'E!': 236,
    'BRAVO': 237,
    'REELZ': 238,
    'SUNDANCETV': 239,
    'HSN': 240,
    'PARAMOUNT NETWORK': 241,
    'USA NETWORK': 242,
    'SYFY': 244,
    'TNT': 245,
    'TRUTV': 246,
    'TBS': 247,
    'FX': 248,
    'COMEDY CENTRAL': 249,
    'OXYGEN TRUE CRIME': 251,
    'LIFETIME': 252,
    'LMN': 253,
    'AMC': 254,
    'TCM': 256,
    'FX MOVIE CHANNEL': 258,
    'FXX': 259,
    'WE TV': 260,
    'DISCOVERY LIFE': 261,
    'BBC AMERICA': 264,
    'A AND E': 265,
    'FYI': 266,
    'EARTHX': 267,
    'HISTORY': 269,
    'VICE': 271,
    'LOGO': 272,
    'POP TV': 273,
    'OVATION': 274,
    'NATIONAL GEOGRAPHIC': 276,
    'TRAVEL CHANNEL': 277,
    'DISCOVERY': 278,
    'OWN': 279,
    'TLC': 280,
    'DISCOVERY TURBO': 281,
    'ANIMAL PLANET': 282,
    'NAT GEO WILD': 283,
    'SCIENCE': 284,
    'INVESTIGATION DISCOVERY': 285,
    'DESTINATION AMERICA': 286,
    'AMERICAN HEROES CHANNEL': 287,
    'PBS KIDS': 288,
    'DISNEY JUNIOR': 289,
    'DISNEY CHANNEL': 290,
    'DISNEY CHANNEL WEST': 291,
    'DISNEY XD': 292,
    'BABYFIRST TV': 293,
    'DISCOVERY FAMILY CHANNEL': 294,
    'METV TOONS': 295,
    'CARTOON NETWORK EAST': 296,
    'CARTOON NETWORK WEST': 297,
    'BOOMERANG': 298,
    'NICKELODEON': 299,
    'NICKELODEON WEST': 300,
    'NICK JR': 301,
    'NICKTOONS': 302,
    'TEENNICK': 303,
    'TV LAND': 304,
    'ION TELEVISION': 305,
    'NEWSNATION': 307,
    'LOOLOO KIDS': 308,
    'HSN 2': 310,
    'FREEFORM': 311,
    'HALLMARK CHANNEL': 312,
    'JEWELRY TV': 313,
    'FAMILY MOVIE CLASSICS': 314,
    'QVC2': 315,
    'QVC': 317,
    'QVC3': 318,
    'SCIENTOLOGY NETWORK': 320,
    'FETV': 323,
    'IN TOUCH PLUS': 324,
    'GREAT AMERICAN FAMILY': 326,
    'CMT': 327,
    'TV ONE': 328,
    'BET': 329,
    'BET HER': 330,
    'MTV': 331,
    'MTV2': 332,
    'IFC': 333,
    'REVOLT': 334,
    'VH1': 335,
    'MTV CLASSIC': 336,
    'UPTV': 338,
    'FUSE': 339,
    'AXS TV': 340,
    'CLEO TV': 341,
    'THEGRIO': 342,
    'I24 NEWS': 343,
    'SONLIFE BROADCASTING NETWORK': 344,
    'RFD TV': 345,
    'BBC NEWS': 346,
    'THE FIRST': 347,
    'FREE SPEECH TV': 348,
    'NEWSMAX': 349,
    'C-SPAN': 350,
    'C-SPAN2': 351,
    'BLOOMBERG TV': 353,
    'CHEDDAR NEWS': 354,
    'CNBC': 355,
    'MS NOW': 356,
    'CNBC WORLD': 357,
    'CNN INTERNATIONAL': 358,
    'FOX BUSINESS NETWORK': 359,
    'FOX NEWS CHANNEL': 360,
    'ACCUWEATHER': 361,
    'WEATHER CHANNEL': 362,
    'FOX WEATHER': 363,
    'INSP': 364,
    'GOD TV': 365,
    'VICTORY': 366,
    'WORLD HARVEST TELEVISION': 367,
    'HOPE CHANNEL': 368,
    'DAYSTAR': 369,
    'EWTN': 370,
    'TBN INSPIRE': 371,
    'TRINITY BROADCASTING NETWORK': 372,
    'WORD NETWORK': 373,
    'BYUTV': 374,
    'BLOSSOM': 375,
    'CTN': 376,
    'TCT NETWORK': 377,
    'NRB': 378,
    'LIVING FAITH NETWORK': 379,
    'IMPACT': 380,
    'ASPIRE': 381,
    'COMEDY TV': 382,
    'JUSTICE CENTRAL': 383,
    'HEROES AND ICONS': 385,
    'FM2': 386,
    'RECIPE TV': 387,
    'JBS': 388,
    'AQUI': 401,
    'UNIVISION EAST': 402,
    'UNIVISION WEST': 403,
    'GALAVISION': 404,
    'UNIMAS': 408,
    'UNIVERSO': 410,
    'CNN EN ESPANOL': 419,
    'CANAL ONCE': 447,
    'ENLACE': 448,
    'ESNE': 456,
    'HITN': 461,
    'DAYSTAR ESPANOL': 463,
    'TUDN': 464,
    'HBO EAST': 501,
    'HBO HITS': 502,
    'HBO DRAMA': 503,
    'HBO WEST': 504,
    'HBO HITS WEST': 505,
    'HBO COMEDY': 506,
    'HBO MOVIES': 509,
    'HBO LATINO': 511,
    'CINEMAX EAST': 515,
    'CINEMAX WEST': 516,
    'CINEMAX HITS': 517,
    'CINEMAX ACTION': 519,
    'CINEMAX CLASSICS': 520,
    'CINEMAX': 523,
    'STARZ': 525,
    'STARZ WEST': 526,
    'STARZ KIDS AND FAMILY': 527,
    'STARZ COMEDY': 528,
    'STARZ EDGE': 529,
    'STARZ IN BLACK': 530,
    'STARZ CINEMA': 531,
    'STARZ ENCORE': 535,
    'STARZ ENCORE WEST': 536,
    'STARZ ENCORE CLASSIC': 537,
    'STARZ ENCORE WESTERNS': 538,
    'STARZ ENCORE SUSPENSE': 539,
    'STARZ ENCORE BLACK': 540,
    'STARZ ENCORE ACTION': 541,
    'STARZ ENCORE FAMILY': 542,
    'PARAMOUNT PLUS WITH SHOWTIME EAST': 545,
    'PARAMOUNT PLUS WITH SHOWTIME WEST': 546,
    'SHOWTIME 2': 547,
    'SHOXBET': 548,
    'SHOWTIME EXTREME': 549,
    'SHOWTIME SHOWCASE': 550,
    'SHOWTIME NEXT': 551,
    'THE MOVIE CHANNEL EAST': 553,
    'THE MOVIE CHANNEL WEST': 554,
    'THE MOVIE CHANNEL XTRA EAST': 555,
    'FLIX': 556,
    'MGM PLUS': 558,
    'MGM PLUS HITS': 559,
    'MGM PLUS MARQUEE': 560,
    'LIONSGATE COLLECTION': 561,
    'SO YUMMY': 563,
    'HALLMARK FAMILY': 564,
    'HALLMARK MYSTERY': 565,
    'HDNET MOVIES': 566,
    'TRIBECA FESTIVAL PLUS': 567,
    'SONY MOVIES': 568,
    'SMITHSONIAN CHANNEL': 570,
    'CRIME AND INVESTIGATION': 571,
    'MTV LIVE': 572,
    'SHORTSTV': 573,
    'FANDUEL TV': 602,
    'COWBOY CHANNEL': 603,
    'PURSUIT': 604,
    'SPORTSMAN CHANNEL': 605,
    'OUTDOOR CHANNEL': 606,
    'BIG TEN NETWORK': 610,
    'SEC NETWORK': 611,
    'ACC NETWORK': 612,
    'FS2': 618,
    'NEXT LEVEL SPORTS': 623,
    'WILLOW': 625,
    'NESN': 628,
    'NBC SPORTS BOSTON': 630,
    'YES NETWORK': 631,
    'MSG': 634,
    'MSG SPORTSNET': 635,
    'SNY': 639,
    'MASN': 640,
    'MONUMENTAL SPORTS NETWORK': 642,
    'FANDUEL SPORTS SOUTH': 646,
    'FANDUEL SPORTS SOUTHEAST': 649,
    'FANDUEL SPORTS SUN': 653,
    'FANDUEL SPORTS FLORIDA': 654,
    'SPORTSNET PITTSBURGH': 659,
    'FANDUEL SPORTS OHIO': 660,
    'FANDUEL SPORTS CINCINNATI': 661,
    'FANDUEL SPORTS DETROIT': 663,
    'MARQUEE SPORTS NETWORK': 664,
    'CHICAGO SPORTS NETWORK': 665,
    'FANDUEL SPORTS NORTH': 668,
    'FANDUEL SPORTS WISCONSIN': 669,
    'FANDUEL SPORTS MIDWEST': 671,
    'SPACE CITY HOME NETWORK': 674,
    'FANDUEL SPORTS OKLAHOMA': 675,
    'FANDUEL SPORTS SOUTHWEST': 676,
    'ALTITUDE SPORTS': 681,
    'SPECTRUM SPORTSNET LOS ANGELES': 690,
    'SPECTRUM SPORTSNET': 691,
    'ANGELS BROADCAST TELEVISION': 692,
    'FANDUEL SPORTS SOCAL': 693,
    'NBC SPORTS BAY AREA': 696,
    'NBC SPORTS CALIFORNIA': 698,
    'IHEARTRADIO': 799,
  };
  static const aliases = <String,String>{
    'FOX NEWS CHANNEL':'FOX NEWS CHANNEL',
    'FOX BUSINESS':'FOX BUSINESS NETWORK',
    'ESPN NEWS':'ESPNEWS',
    'ESPN U':'ESPNU',
    'ESPN 2':'ESPN2',
    'FOX SPORTS ONE':'FS1',
    'FOX SPORTS TWO':'FS2',
    'NAT GEO':'NATIONAL GEOGRAPHIC',
    'NAT GEO WILD':'NAT GEO WILD',
    'FXM':'FX MOVIE CHANNEL',
    'CSPAN':'C-SPAN',
    'CSPAN 2':'C-SPAN2',
    'BLOOMBERG':'BLOOMBERG TV',
    'MSNBC':'MS NOW',
    'THE HISTORY CHANNEL':'HISTORY',
    'THE WEATHER CHANNEL':'WEATHER CHANNEL',
    'SCIFI':'SYFY',
    'SCIENCE CHANNEL':'SCIENCE',
    'A&E':'A AND E',
    'NICK JR.':'NICK JR',
    'NICK JR':'NICK JR',
    'ION':'ION TELEVISION',
    'FOX SPORTS 1':'FS1',
    'FOX SPORTS 2':'FS2',
    'REELZ CHANNEL':'REELZ',
    'THE LEARNING CHANNEL':'TLC',
  };
  // Provider titles often have regional prefixes, group tags and bitrate labels.
  // Match conservatively against known network names, never substrings:
  // ESPN, ESPN2, ESPNU and ESPN News must remain different stations.
  static const _synonyms=<String,String>{
    'A&E':'A AND E','AE':'A AND E','A AND E NETWORK':'A AND E',
    'FX NETWORK':'FX','FX HD':'FX','FXX HD':'FXX',
    'NAT GEO':'NATIONAL GEOGRAPHIC','NAT GEO CHANNEL':'NATIONAL GEOGRAPHIC',
    'NATIONAL GEO':'NATIONAL GEOGRAPHIC','NATIONAL GEOGRAPHIC CHANNEL':'NATIONAL GEOGRAPHIC',
    'DISCOVERY CHANNEL':'DISCOVERY',
    'HISTORY CHANNEL':'HISTORY','THE HISTORY CHANNEL':'HISTORY',
    'COMEDY CENTRAL HD':'COMEDY CENTRAL',
    'FOX SPORTS 1':'FS1','FOX SPORTS ONE':'FS1','FOX SPORTS 2':'FS2',
    'FOX NEWS':'FOX NEWS CHANNEL','FOX BUSINESS':'FOX BUSINESS NETWORK',
    'ESPN 2':'ESPN2','ESPN TWO':'ESPN2','ESPN NEWS':'ESPNEWS',
    'ESPN U':'ESPNU','ESPNU HD':'ESPNU',
    'CBS SPORTS':'CBS SPORTS NETWORK','CBS SN':'CBS SPORTS NETWORK',
    'NBC SPORTS':'NBC SPORTS NETWORK',
    'SYFY CHANNEL':'SYFY','SCI FI':'SYFY','SCI-FI':'SYFY',
    'MSNBC':'MS NOW','ION':'ION TELEVISION','ION TV':'ION TELEVISION',
    'TCM US':'TCM','TURNER CLASSIC MOVIES':'TCM',
    'AMC US':'AMC','AMC CHANNEL':'AMC','TNT US':'TNT',
    'TLC US':'TLC','THE LEARNING CHANNEL':'TLC',
    'USA':'USA NETWORK','USA CHANNEL':'USA NETWORK',
    'BET CHANNEL':'BET','BBC AMERICA US':'BBC AMERICA',
    'WEATHER CHANNEL':'WEATHER CHANNEL',
    'THE WEATHER CHANNEL':'WEATHER CHANNEL',
    'NICK JR':'NICK JR','NICK JUNIOR':'NICK JR',
    'CSPAN':'C-SPAN','CSPAN 2':'C-SPAN2',
    'BLOOMBERG':'BLOOMBERG TV',
    'FOOD':'FOOD NETWORK','HGTV US':'HGTV',
  };
  static String canonical(String raw) {
    var s=raw.toUpperCase().trim();
    // Strip prefixes such as |NA|, [US], USA:, CA -, and provider group tags.
    for(var i=0;i<4;i++){
      final next=s.replaceFirst(RegExp(
        r'^\s*(?:[|\[(]\s*)?(?:US|USA|CA|CAN|CANADA|NA|NORTH AMERICA|UK|EN|ENG|ENGLISH|AU|NZ|LIVE|TV|VIP|SPORTS|ENTERTAINMENT)\s*(?:[|\])]|[:\-]\s*|\s+)',caseSensitive:false),'').trim();
      if(next==s||next.isEmpty)break;
      s=next;
    }
    s=s.replaceAll(RegExp(r'\[[^\]]*(?:HD|UHD|FHD|4K|SD|HEVC)[^\]]*\]'),' ')
      .replaceAll(RegExp(r'\([^)]*(?:HD|UHD|FHD|4K|SD|HEVC)[^)]*\)'),' ')
      .replaceAll(RegExp(r'\b(?:4K|UHD|FHD|HD|HEVC|H265|H264|1080P|720P|SD|BACKUP|SOURCE|RAW|VIP)\b'),' ')
      .replaceAll(RegExp(r'\s+'),' ').trim()
      .replaceFirst(RegExp(r'^\d{2,4}\s*[-:.]\s*'),'');
    s=_synonyms[s]??aliases[s]??s;
    return s;
  }
  static String _key(String text)=>canonical(text).replaceAll(RegExp(r'[^A-Z0-9]'),'');
  static final Map<String,int> _byKey={
    for(final entry in reference.entries)_key(entry.key):entry.value,
  };
  static int? referenceNumber(MediaEntry item) => matchNumber(item.title);
  static int? matchNumber(String title) {
    final exact=_byKey[_key(title)];
    if(exact!=null)return exact;
    // A trailing country marker should not affect station identity.
    final clean=canonical(title).replaceFirst(
      RegExp(r'\s+(?:US|USA|CA|CANADA|UK|EAST COAST|WEST COAST)$'),'');
    return _byKey[_key(clean)];
  }
  static int _quality(MediaEntry item){
    final title=item.title.toUpperCase();
    var points=item.likelyEnglish?10:0;
    if(title.contains('FHD')||title.contains('1080'))points+=6;
    if(title.contains(' HD'))points+=4;
    if(item.artwork.startsWith('http'))points+=2;
    if(item.epgId.isNotEmpty)points+=3;
    return points;
  }
  static Map<int,MediaEntry> matched(List<MediaEntry> all){
    final matches=<int,MediaEntry>{};
    for(final item in all){
      final number=referenceNumber(item);
      if(number==null)continue;
      final current=matches[number];
      if(current==null||_quality(item)>_quality(current))matches[number]=item;
    }
    return matches;
  }
  static List<MediaEntry> curated(List<MediaEntry> all){
    final selected=matched(all);
    final numbers=selected.keys.toList()..sort();
    return numbers.map((n)=>selected[n]!).toList();
  }
}
